import { defineConfig } from 'vite';
import fs from 'node:fs/promises';
import path from 'node:path';
import { renderPage } from './scripts/html-compiler.mjs';
import tailwindcss from '@tailwindcss/vite';
import siteConfig from './site.config.js';

export default defineConfig({
    root: 'src',
    publicDir: '../public',
    // Resolve peer dependencies (htmx.org, handlebars, sortablejs) from the app's
    // node_modules, not from inside the framework's file: linked directory.
    resolve: {
        dedupe: ['htmx.org', 'handlebars', 'sortablejs'],
    },
    // Our HTML pages are generated by a dev middleware (not served directly as root index.html),
    // so Vite can't reliably auto-detect an entrypoint for dependency pre-bundling.
    // Tell it explicitly to avoid the "Could not auto-determine entry point" warning.
    optimizeDeps: {
        entries: ['app.js'],
        include: ['htmx.org', 'handlebars', 'sortablejs'],
    },
    server: {
        // Dev-only: proxy same-origin `/api/*` calls to the Handlr backend.
        //
        // Run Handlr separately (e.g. `http://localhost:8000`) and set:
        //   HANDLR_ORIGIN=http://localhost:8000 npm run dev
        proxy: {
            '/api': {
                target: process.env.HANDLR_ORIGIN || 'http://localhost:8000',
                changeOrigin: false,
                secure: false,
            },
        },
    },
    plugins: [
        tailwindcss(),
        {
            name: 'dev-baked-pages',
            apply: 'serve',
            configureServer(server) {
                const projectRoot = process.cwd();
                const layoutsDir = path.join(projectRoot, 'content', 'layouts');
                const pagesDir = path.join(projectRoot, 'content', 'pages');
                const componentsDir = path.join(projectRoot, 'content', 'components');
                const siteName = siteConfig.siteName || 'Site';

                function normalizeUrlPath(urlPath) {
                    if (!urlPath) return '/';
                    if (urlPath === '/') return '/';
                    return urlPath.endsWith('/') ? urlPath : `${urlPath}/`;
                }

                function titleFromUrlPath(urlPath) {
                    const p = normalizeUrlPath(urlPath);
                    if (p === '/') return '';
                    const segs = p
                        .replace(/^\/|\/$/g, '')
                        .split('/')
                        .filter(Boolean);
                    const last = segs[segs.length - 1] || 'Page';
                    return last
                        .split(/[-_]+/g)
                        .filter(Boolean)
                        .map((w) => w[0].toUpperCase() + w.slice(1))
                        .join(' ');
                }

                async function fileExists(p) {
                    try {
                        await fs.access(p);
                        return true;
                    } catch {
                        return false;
                    }
                }

                async function listHtmlFiles(dir) {
                    const out = [];
                    const entries = await fs.readdir(dir, { withFileTypes: true });
                    for (const ent of entries) {
                        const full = path.join(dir, ent.name);
                        if (ent.isDirectory()) {
                            out.push(...(await listHtmlFiles(full)));
                        } else if (ent.isFile() && ent.name.toLowerCase().endsWith('.html') && !ent.name.startsWith('_')) {
                            out.push(full);
                        }
                    }
                    return out;
                }

                function templatePathToRoute(relPath) {
                    // Convert template path to route pattern
                    // e.g., "series/[id]/collections.html" -> "/series/[id]/collections/"
                    // e.g., "series/[id]/index.html" -> "/series/[id]/"
                    const rel = relPath.replaceAll(path.sep, '/');
                    if (rel === 'index.html') return '/';

                    const dir = path.posix.dirname(rel);
                    const base = path.posix.basename(rel);

                    if (base === 'index.html') {
                        return `/${dir}/`.replace(/\/\//g, '/');
                    }

                    const name = base.slice(0, -'.html'.length);
                    return `/${dir === '.' ? '' : `${dir}/`}${name}/`.replace(/\/\//g, '/');
                }

                function matchesRoutePattern(urlPath, patternRoute) {
                    // Check if a URL path matches a route pattern with [param] placeholders
                    // e.g., "/series/abc123/collections/" matches "/series/[id]/collections/"
                    const urlNorm = normalizeUrlPath(urlPath);
                    const patternNorm = normalizeUrlPath(patternRoute);

                    const urlSegments = urlNorm.replace(/^\/|\/$/g, '').split('/').filter(Boolean);
                    const patternSegments = patternNorm.replace(/^\/|\/$/g, '').split('/').filter(Boolean);

                    if (urlSegments.length !== patternSegments.length) return false;

                    for (let i = 0; i < urlSegments.length; i++) {
                        const patternSeg = patternSegments[i];
                        const urlSeg = urlSegments[i];

                        // Dynamic segment [param] matches anything
                        if (patternSeg.startsWith('[') && patternSeg.endsWith(']')) {
                            continue;
                        }

                        // Static segment must match exactly
                        if (urlSeg !== patternSeg) {
                            return false;
                        }
                    }

                    return true;
                }

                async function findDynamicRoute(urlPath) {
                    try {
                        const allFiles = await listHtmlFiles(pagesDir);

                        for (const filePath of allFiles) {
                            const rel = path.relative(pagesDir, filePath);
                            const routePattern = templatePathToRoute(rel);

                            if (matchesRoutePattern(urlPath, routePattern)) {
                                return filePath;
                            }
                        }
                    } catch {
                        // If directory scanning fails, return null
                    }

                    return null;
                }

                async function resolvePagePath(urlPath) {
                    const p = normalizeUrlPath(urlPath);
                    if (p === '/') return path.join(pagesDir, 'index.html');

                    const rel = p.replace(/^\/|\/$/g, '');
                    const direct = path.join(pagesDir, `${rel}.html`);
                    const index = path.join(pagesDir, rel, 'index.html');

                    // First try exact matches
                    if (await fileExists(direct)) return direct;
                    if (await fileExists(index)) return index;

                    // If no exact match, try dynamic routes with [param] patterns
                    return await findDynamicRoute(urlPath);
                }

                async function renderRoute(urlPath) {
                    const pagePath = await resolvePagePath(urlPath);
                    if (!pagePath) return null;

                    return await renderPage({
                        layoutsDir,
                        pagePath,
                        title: titleFromUrlPath(urlPath),
                        componentsDir,
                        siteConfig,
                        // In dev, Vite serves these directly from the `root: 'src'` directory.
                        jsSrc: '/app.js',
                        // CSS is imported by app.js; leaving this null avoids double-loading.
                        cssHref: null,
                    });
                }

                server.middlewares.use(async (req, res, next) => {
                    try {
                        if (req.method !== 'GET') return next();

                        const url = (req.url || '/').split('?')[0];

                        // Skip static assets — only handle page routes (.html or extensionless)
                        const ext = path.extname(url).toLowerCase();
                        if (ext && ext !== '.html') return next();

                        const urlPath = normalizeUrlPath(url);

                        const html = await renderRoute(urlPath);
                        if (!html) return next();

                        // Let Vite inject HMR client, env replacements, etc.
                        const transformed = await server.transformIndexHtml(url, html);

                        res.statusCode = 200;
                        res.setHeader('Content-Type', 'text/html');
                        res.end(transformed);
                    } catch (err) {
                        next(err);
                    }
                });
            },
        },
    ],
    build: {
        outDir: '../dist',
        assetsDir: 'assets',
        manifest: true,
        emptyOutDir: true,
        rollupOptions: {
            input: {
                app: './src/app.js',
            },
            onwarn(warning, warn) {
                // htmx uses `eval()` internally (and in some bundled extensions).
                // Vite/Rollup surfaces that as an EVAL warning; we intentionally
                // keep htmx, but we don't want this single dependency to spam builds.
                if (
                    warning?.code === 'EVAL' &&
                    typeof warning?.id === 'string' &&
                    warning.id.includes('/node_modules/htmx.org/')
                ) {
                    return;
                }

                warn(warning);
            },
        },
    },
});
